TOPDIR=../..

BUILD_ANT_SUBDIR=$(TOPDIR)/
BUILD_ANT_JARFILE=$(TOPDIR)/build/core-renderer.jar
BUILD_ANT_TARGET=jar

INSTALL_USER=y
INSTALL_ADMIN=y
INSTALL_SERVICE=y
INSTALL_LIB=y
INSTALL_ZIMLET=y

include $(TOPDIR)/common.mk
include $(ZIMBRA_BUILD_ROOT)/extensions-extra/zmpkg/mk/zcs-java-lib-ant.mk
